chore: Update Go version in prow-tests image
knative/infra pull request #130
Opened 2023-07-17 09:23 UTC by dsimansk

Bump Go version in `prow-tests` before next release per @dprotaso suggestion. 

/cc @dprotaso 
/cc @knative/knative-release-leads

2023-07-17 09:25 UTC, pierDipi approved these changes
/lgtm
/approve

2023-07-17 09:33 UTC, dsimansk commented
/test pull-knative-infra-prow-tests-image-build

2023-07-17 13:08 UTC, upodroid requested changes
You can go ahead and add it, assuming it doesn't break serving, eventing, etc

2023-07-17 16:15 UTC, dsimansk commented
/hold

2023-07-18 09:43 UTC, dsimansk commented on images/prow-tests/Dockerfile
> +
@upodroid the image builds fine with `CGO_ENABLED`. Is there a way to verify Serving, Eventing other than merging the PR and runnings builds on the respective repos afterwards.

2023-07-18 10:18 UTC, dsimansk commented
/unhold

2023-07-18 10:22 UTC, upodroid approved these changes
No, we have to use the image and see what happens.

2023-07-18 10:23 UTC, merged